### ISSUE TITLE
Shutdown PC ignores settings

### ISSUE THREAD

**Issue by halfh** [iPollox/BDAC#1]
The setting for shutting down PC was disabled, yet it turned off my PC after I had an afk disconnect.
Did a test with it disabled and just running BDO launcher and logging in, so that the app still showed BDO as disconnected. BDO was closed than it started the 5 minute countdown right away.

**Comment by OS-Void** [comment]
Sorry for the delay, I got occupied with the holidays, work and school.
It should be fixed now.
